name: flutter_credit_card_new
description: A Credit Card widget package, support entering card details, card flip animation.
version: 0.0.4
homepage: https://github.com/raviganwal/flutter_credit_card.git
issue_tracker: https://github.com/raviganwal/flutter_credit_card/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - icons/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf
